# Generated by Django 4.2.5 on 2023-09-11 17:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_date', models.DateField(default=datetime.date.today)),
                ('status', models.SmallIntegerField(choices=[(1, 'Live'), (2, 'Pending'), (3, 'Archived')])),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('type', models.SmallIntegerField(choices=[(1, 'Survey'), (2, 'Discussion'), (3, 'Diary')])),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.tile')),
            ],
        ),
    ]
